### ISSUE TITLE
Export isn't working on latest on CurseForge.

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GDKPd-Classic#49]
Hey @xpwn3rx,

Reports that the export feature is no longer working.

https://discord.com/channels/990821777875800094/1021972047951302668/1072656696687743046

**Comment by KaylinFinke** [comment]
@xpwn3rx can you explain in more detail what issue you're having with this feature?

**Comment by xpwn3rx** [comment]
This was opened by Gogo after messaging me on Discord. The person saying this didn't work was getting errors related to stored raids, not related to this mod. He had to clear data in his existing stored raids to get the errors to stop. All exports were broken, not just the ones I added. The at was pinging me via Github since I forked, modified and setup a pull request.

**Comment by KaylinFinke** [comment]
Do you think we can close this then?

**Comment by xpwn3rx** [comment]
Yes, absolutely
