### ISSUE TITLE
auctioning items with the same name doesn't auto queue

### ISSUE THREAD

**Issue by knasen88** [Gogo1951/GDKPd-Classic#55]
title pretty much, auctioning for example multiple vanquisher regalias in a row doesn't automatically make them go in sequence.

i believe it's tied to the "staging feature" but there is no option to enable or disable it? #52

**Comment by KaylinFinke** [comment]
Not a bug. The existing protocol has never allowed multiple active auctions for the same item.

**Comment by knasen88** [comment]
Ah so if people were running older versions of the addon and the ML queued same item twice it would then just fail to show up on their end?

I see, thanks

**Comment by KaylinFinke** [comment]
It's actually true with this version as well not just older versions. The addon communication for items (not chat) that aren't being actively bid unfortunately differentiates by item ID instead of an auction guid or something. Without releasing a 2.0 I didn't think of a good way to add this. You could probably get it to re-do an auction for the same item type without warning (not fun as now the queue is a lie), or queue one once the queue clears if there's one of that type in the queue, or not allow the ML to queue items if there's 2 of the same type queued (which all have similar drawbacks). I felt that behavior was more surprising and didn't indicate to users that there might be more items coming in the current auction queue than just letting somebody do it manually similar to the manual auction start feature.

**Comment by KaylinFinke** [comment]
Thank-you for the report though. No harm done and if you find any other bugs or concerning things please don't hesitate to reach out.
